all: one.sample one.input two.sample two.input

one.sample:
	dotnet fsi one.fsx < input.sample
one.input:
	dotnet fsi one.fsx < input
two.sample:
	dotnet fsi two.fsx < input.sample
two.input:
	dotnet fsi two.fsx < input
