all: one.sample one.input two.sample two.input 

one.sample:
	tsc
	node one.js < input.sample
one.input:
	tsc
	node one.js < input
two.sample:
	tsc
	node two.js < input.sample
two.input:
	tsc
	node two.js < input
