all: one.sample one.input two.sample two.input

one.input: 
	nodejs one.js < input
one.sample: 
	nodejs one.js < input.sample

two.input: 
	nodejs two.js < input
two.sample: 
	nodejs two.js < input.sample
